@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.chemlib._datagen_disabled;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;